name: Node.js Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

  deploy:
    runs-on: ubuntu-latest
    needs: publish
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'express-rest'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4871251DF82D44B9A464765CAF97E7FE }}
          package: .

      - name: Start Server on Azure Web App
        run: |
          cd $HOME/site/wwwroot
          npm install
          npm start
